print('----------Criador HTML----------')
titulo = input('Insira um título para a página:')
cabecalho = input('Insira um texto de cabeçalho:')
link1 = input('Insira um link:')
link2 = input('Insira o segundo link:')
desclink1 = input('Insira a descrição para o primeiro link:')
desclink2 = input('Insira a descrição para o segundo link:')

arquivo = open("resultadohtml.html", 'w')
arquivo.write('<html><head><title>{}</title></head>'.format(titulo))
arquivo.write('\n<body><head><h1>{}</h1></head>'.format(cabecalho))
arquivo.write('\n<a href="https://{}">{}</a>'.format(link1, desclink1))
arquivo.write('\n<a href="https://{}">{}</a>'.format(link2, desclink2))
arquivo.close()
